spring.application.name=demo
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.model=gpt-4o-mini
spring.ai.openai.chat.temperature=0.8
spring.ai.model.audio.transcription=openai
spring.ai.openai.audio.transcription.temperature=0.2
spring.ai.openai.audio.transcription.language=pt
spring.ai.openai.audio.transcription.response-format=text

spring.ai.openai.audio.speech.model=gpt-4o-mini-tts
spring.ai.openai.audio.speech.voice=nova
spring.ai.openai.audio.speech.speed=1.2
spring.ai.openai.audio.speech.response-format=mp3

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5433/budgetingdb
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true