spring.application.name=demo
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.model=gpt-4o-mini
spring.ai.openai.chat.temperature=0.8
spring.ai.model.audio.transcription=openai
spring.ai.openai.audio.transcription.temperature=0.2
spring.ai.openai.audio.transcription.language=pt
spring.ai.openai.audio.transcription.response-format=text
